"""Pydantic domain models."""

from upskills.models.domain.auth import (
    AuthResponse,
    LoginRequest,
    RefreshTokenRequest,
    RegisterRequest,
    TokenPayload,
    TokenResponse,
)
from upskills.models.domain.base import DomainModel, MessageResponse, PaginatedResponse
from upskills.models.domain.career import (
    CareerCreate,
    CareerResponse,
    CareerUpdate,
    CareerWithPathsResponse,
    PathStepCreate,
    PathStepDependencyResponse,
    PathStepResponse,
    PathStepUpdate,
    PathTemplateCreate,
    PathTemplateResponse,
    PathTemplateUpdate,
    PathTemplateWithStepsResponse,
    StepDependencyCreate,
)
from upskills.models.domain.progress import (
    DashboardStats,
    LogEntryCreate,
    LogEntryDetailResponse,
    LogEntryResponse,
    LogEntryType,
    LogEntryUpdate,
    MenteeProgressSummary,
    ProgressStatus,
    UserCareerPathCreate,
    UserCareerPathDetailResponse,
    UserCareerPathResponse,
    UserCareerPathUpdate,
    UserPathAssignmentCreate,
    UserPathAssignmentDetailResponse,
    UserPathAssignmentResponse,
    UserPathAssignmentUpdate,
    UserStepProgressResponse,
    UserStepProgressUpdate,
    ValidationStatus,
)
from upskills.models.domain.team import (
    TeamCreate,
    TeamListResponse,
    TeamMemberAdd,
    TeamMemberBulkAdd,
    TeamMemberResponse,
    TeamResponse,
    TeamUpdate,
    TeamWithMembersResponse,
)
from upskills.models.domain.user import (
    ActionResponse,
    PasswordChange,
    PasswordReset,
    PasswordResetRequest,
    RoleResponse,
    UserCreate,
    UserInDB,
    UserResponse,
    UserUpdate,
    UserWithPermissions,
)

__all__ = [
    "ActionResponse",
    "AuthResponse",
    # Career
    "CareerCreate",
    "CareerResponse",
    "CareerUpdate",
    "CareerWithPathsResponse",
    "DashboardStats",
    # Base
    "DomainModel",
    "LogEntryCreate",
    "LogEntryDetailResponse",
    "LogEntryResponse",
    "LogEntryType",
    "LogEntryUpdate",
    # Auth
    "LoginRequest",
    "MenteeProgressSummary",
    "MessageResponse",
    "PaginatedResponse",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetRequest",
    "PathStepCreate",
    "PathStepDependencyResponse",
    "PathStepResponse",
    "PathStepUpdate",
    "PathTemplateCreate",
    "PathTemplateResponse",
    "PathTemplateUpdate",
    "PathTemplateWithStepsResponse",
    # Progress
    "ProgressStatus",
    "RefreshTokenRequest",
    "RegisterRequest",
    "RoleResponse",
    "StepDependencyCreate",
    # Team
    "TeamCreate",
    "TeamListResponse",
    "TeamMemberAdd",
    "TeamMemberBulkAdd",
    "TeamMemberResponse",
    "TeamResponse",
    "TeamUpdate",
    "TeamWithMembersResponse",
    "TokenPayload",
    "TokenResponse",
    "UserCareerPathCreate",
    "UserCareerPathDetailResponse",
    "UserCareerPathResponse",
    "UserCareerPathUpdate",
    # User
    "UserCreate",
    "UserInDB",
    "UserPathAssignmentCreate",
    "UserPathAssignmentDetailResponse",
    "UserPathAssignmentResponse",
    "UserPathAssignmentUpdate",
    "UserResponse",
    "UserStepProgressResponse",
    "UserStepProgressUpdate",
    "UserUpdate",
    "UserWithPermissions",
    "ValidationStatus",
]
